name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install NPM packages
      run: npm ci
      
    - name: Eslint
      run: npm run lint

    - name: Test run
      run: npm run test
